packaging_format = 2

id = "contacts-libres-cnt"
name = "Contacts Libres CNT-AIT"
description.en = "Decentralized contact manager for anarcho-syndicalist militants and affinity groups"
description.fr = "Gestionnaire de contacts décentralisé pour militants anarcho-syndicalistes et groupes affinitaires"

version = "1.0~ynh1"

maintainers = ["CNT-AIT Community"]

[upstream]
license = "MIT"
website = "https://github.com/Jesusiunchatnoir/contact-cnt-ait_ynh"
demo = "https://github.com/Jesusiunchatnoir/contact-cnt-ait_ynh"
admindoc = "https://github.com/Jesusiunchatnoir/contact-cnt-ait_ynh"
userdoc = "https://github.com/Jesusiunchatnoir/contact-cnt-ait_ynh/blob/main/README.md"
code = "https://github.com/Jesusiunchatnoir/contact-cnt-ait_ynh"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "200M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/contacts"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    help.en = "Admin password for the application"
    help.fr = "Mot de passe administrateur pour l'application"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/Jesusiunchatnoir/contact-cnt-ait_ynh/archive/refs/heads/main.tar.gz"
        sha256 = "1f37a069bf8e4a9d90c1a8abfa93a73d7e71eba3c047dfda5a656d4065bbedf6"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
        main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "nodejs, npm, sqlite3, build-essential"
